apiVersion: apps/v1
kind: Deployment
metadata:
  name: administration-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: administration
  template:
    metadata:
      labels:
        app: administration
    spec:
      containers:
        - image: as9721/administration:2023-01-09-21-56-26
          name: administration
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
            - containerPort: 9090
              name: grpc
              protocol: TCP
          env:
            - name: spring.datasource.url
              value: jdbc:mysql://primerjalnik-cen-server.mysql.database.azure.com:3306/primerjalnik-cen?useSSL=true
            - name: spring.datasource.username
              value: adminRso
            - name: spring.datasource.password
              value: Rso2022@
            - name: LOGBACK_DESTINATION
              value: aab8af63-1013-422f-8043-7012c08ace36-ls.logit.io:27798
            - name: CONFIG_SERVER_URL
              value: http://20.4.194.189:8888
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: administration
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
      name: server
    - port: 9090
      protocol: TCP
      targetPort: grpc
      name: grpc
  selector:
    app: administration
