apiVersion: apps/v1
kind: Deployment
metadata:
  name: administration-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: administration
  template:
    metadata:
      labels:
        app: administration
    spec:
      containers:
        - image: as9721/administration:2022-11-29-23-24-37
          name: administration
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: administration
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      protocol: TCP
      targetPort: server
  selector:
    app: administration