apiVersion: apps/v1
kind: Deployment
metadata:
  name: administration-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: administration
  template:
    metadata:
      labels:
        app: administration
    spec:
      containers:
        - image: as9721/administration:2022-11-29-23-24-37
          name: administration
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
          env:
            - name: spring.datasource.url
              value: jdbc:mysql://primerjalnik-cen-server.mysql.database.azure.com:3306/primerjalnik-cen?useSSL=true
            - name: spring.datasource.username
              value: adminRso
            - name: spring.datasource.password
              value: Rso2022@

---

apiVersion: v1
kind: Service
metadata:
  name: administration
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      protocol: TCP
      targetPort: server
  selector:
    app: administration
